### ISSUE TITLE
How to add this plugin to AOSP

### ISSUE THREAD

**Issue by fonic** [DroidsOnRoids/android-gradle-aosp-aapt-plugin#1]
I would like to use this plugin, but I can't figure out how to add it to my AOSP build. Could you give instructions?

**Comment by koral--** [comment]
You can add plugin to your build script (usually `build.gradle`) as any other plugin, snippets are available at [gradle plugin portal](https://plugins.gradle.org/plugin/pl.droidsonroids.aosp.aapt). Note that plugin has to be applied to android application and/or library modules, not to root module.

Of course you also need a gradle-based AOSP modules. I've made them in following way:

### Common macro referenced later in particular `Android.mk` files.

Can be placed in `$(BUILD_SYSTEM)/gradle.mk`:

```
submodule_path := $(LOCAL_PATH)/$(LOCAL_GRADLE_PROJECT_NAME)
apk_relative_path := app/build/outputs/apk/app-release.apk
PRIVATE_SRC_FILES := $(LOCAL_GRADLE_PROJECT_NAME)/$(apk_relative_path)

.PHONY: $(submodule_path)/$(apk_relative_path)
$(submodule_path)/$(apk_relative_path) : 
        PLATFORM_SDK_VERSION="$(PLATFORM_SDK_VERSION)" PRODUCT_AAPT_PREF_CONFIG="$(PRODUCT_AAPT_PREF_CONFIG)" PRODUCT_LOCALES="$(PRODUCT_LOCALES)" $(submodule_path)/gradlew assembleRelease -p $(submodule_path)
```

`$(BUILD_SYSTEM)` is `<root aosp directory>/build/core`. Note that there is hardcoded module name (`app`) and build variant name (`release` without flavor).

### Contents of `Android.mk` files for gradle-bases modules:

```
LOCAL_PATH := $(call my-dir)

LOCAL_GRADLE_PROJECT_NAME := DemoApp
include $(BUILD_SYSTEM)/gradle.mk
include $(CLEAR_VARS)

LOCAL_REQUIRED_MODULES := libdemo
LOCAL_JNI_SHARED_LIBRARIES := libdemo
LOCAL_MODULE_TAGS := debug
LOCAL_MODULE := $(notdir $(LOCAL_PATH))
LOCAL_MODULE_CLASS := APPS
LOCAL_SRC_FILES := $(PRIVATE_SRC_FILES)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)
include $(CLEAR_VARS)
```

Important lines:
- `LOCAL_GRADLE_PROJECT_NAME := DemoApp` - value is a name of the directory of gradle project
- `LOCAL_CERTIFICATE := PRESIGNED` - signingConfig has to be set in `build.gradle`
- `include $(BUILD_PREBUILT)`

Directory structure:

```
├── Demo
│   ├── Android.mk
│   ├── CleanSpec.mk
│   └── DemoApp <- LOCAL_GRADLE_PROJECT_NAME
│       ├── app <- hardcoded gradle module name
│       ├── build.gradle <- release signingConfig and aosp-aapt-plugin
│       ├── gradle.properties
│       ├── gradlew
│       └── settings.gradle
```

**Comment by KrishnaGolakoti** [comment]
Hi Koral,

Could you please let me know if you can share any sample app built with AOSP?

**Comment by koral--** [comment]
Hi,
unfortunately I don't have any complete sample to share.
